# Generated by Django 5.0.14 on 2026-07-26 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PNRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_reference', models.CharField(max_length=32, unique=True)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_pnr', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('itinerary_data', models.JSONField(blank=True, default=dict)),
                ('invoice_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_record', to='booking.booking')),
            ],
            options={
                'db_table': 'ticketing_pnr_record',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('ticket_number', models.CharField(max_length=32, unique=True)),
                ('provider_ticket_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('voided', 'Voided'), ('reissued', 'Reissued'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('coupon_data', models.JSONField(blank=True, default=dict)),
                ('pdf_content', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.bookingpassenger')),
                ('pnr_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.pnrrecord')),
                ('reissue_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reissues', to='ticketing.ticket')),
            ],
            options={
                'db_table': 'ticketing_ticket',
                'ordering': ('-created_at',),
                'unique_together': {('booking', 'passenger', 'reissue_parent')},
            },
        ),
        migrations.CreateModel(
            name='TicketAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('status_from', models.CharField(blank=True, max_length=20)),
                ('status_to', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pnr_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ticketing.pnrrecord')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ticketing.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticketing_audit_event',
                'ordering': ('-created_at',),
            },
        ),
    ]
