# Generated by Django 5.0.14 on 2026-07-26 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancellation_type', models.CharField(choices=[('full', 'Full Booking Cancellation'), ('partial_passengers', 'Partial – Passenger-wise'), ('partial_segments', 'Partial – Segment-wise')], default='full', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cancelled_segment_indexes', models.JSONField(blank=True, default=list, help_text='List of itinerary segment indexes being cancelled (for partial segment cancellation).')),
                ('reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('provider_cancellation_reference', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='booking.booking')),
                ('passengers', models.ManyToManyField(blank=True, related_name='cancellation_requests', to='booking.bookingpassenger')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cancellation_request',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RefundClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('gross_fare', models.DecimalField(decimal_places=2, help_text='Total fare paid by the customer.', max_digits=14)),
                ('airline_penalty', models.DecimalField(decimal_places=2, default=0, help_text='GDS/Airline cancellation fee.', max_digits=14)),
                ('ota_fee', models.DecimalField(decimal_places=2, default=0, help_text='OTA service/processing fee.', max_digits=14)),
                ('net_refund', models.DecimalField(decimal_places=2, help_text='Amount to be refunded to the customer.', max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('settled', 'Settled'), ('failed', 'Failed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('refund_method', models.CharField(blank=True, help_text='e.g., original_payment, credit_wallet', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=150)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_claims', to='booking.booking')),
                ('cancellation_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_claim', to='cancellation.cancellationrequest')),
            ],
            options={
                'db_table': 'refund_claim',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CancellationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('status_from', models.CharField(blank=True, max_length=50)),
                ('status_to', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_audit_events', to=settings.AUTH_USER_MODEL)),
                ('cancellation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='cancellation.cancellationrequest')),
                ('refund_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='cancellation.refundclaim')),
            ],
            options={
                'db_table': 'cancellation_audit_event',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RefundLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('airline_credit', 'Airline Credit'), ('penalty', 'Penalty Deduction'), ('ota_fee', 'OTA Processing Fee'), ('customer_payout', 'Customer Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='cancellation.refundclaim')),
            ],
            options={
                'db_table': 'refund_ledger_entry',
                'ordering': ('created_at',),
            },
        ),
    ]
