# Generated by Django 5.0.14 on 2026-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancellation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='provider_cancellation_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
